### ISSUE TITLE
Написание ТЗ

### ISSUE THREAD

**Issue by AndreiDevyaterikov** [AndreiDevyaterikov/Intensive#6]
Написать техническое задание

**Comment by IlyaLobov-TopCoder** [comment]
ТЗ
[ТЗ 2 вариант.docx](https://github.com/AndreiDevyaterikov/Intensive/files/4366271/2.docx)

**Comment by IlyaLobov-TopCoder** [comment]
__
[ТЗ 2 вариант.docx](https://github.com/AndreiDevyaterikov/Intensive/files/4371079/2.docx)

**Comment by AndreiDevyaterikov** [comment]
https://docs.google.com/document/d/1wpAhSKXgJb49sJB_cILG85v1OCZIKp9kkcEYKQSOMD0/edit
Оформить титульный лист в соответствии с примером по ссылке
Добавить оглавление

**Comment by IlyaLobov-TopCoder** [comment]
[ТЗ 2.1 вариант.docx](https://github.com/AndreiDevyaterikov/Intensive/files/4371465/2.1.docx)

**Comment by AndreiDevyaterikov** [comment]
Нет оглавления

**Comment by IlyaLobov-TopCoder** [comment]
[ТЗ 2.2 вариант.docx](https://github.com/AndreiDevyaterikov/Intensive/files/4380551/2.2.docx)

**Comment by IlyaLobov-TopCoder** [comment]
https://docs.google.com/document/d/1FwqTeZmV2Y9gg8dh3ffTglfBbtneC9KGdUD3SDzasQQ/edit
